name: knowledge_distil
channels: 
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - pytorch==1.8
  - numpy==1.19.5
  - pandas==1.2.4
  - pip:
      - matplotlib==3.4.2